Repository StatCan/volume-cleaner, pull requests merged in 2025-06, with the labels that each got.

#22 Docs(templating): Issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
Labels: documentation

#42 bug(pr template): pull request template will load
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#30 feat: list unattached pvcs
  cmd/volume_cleaner/kubernetes.go
  cmd/volume_cleaner/main.go
  cmd/volume_cleaner/set.go
  cmd/volume_cleaner/set_test.go
  manifests/rbac.yaml
Labels: enhancement

#51 Feat/49 label functions
  internal/kubernetes/labeller.go
  internal/kubernetes/labeller_test.go
  internal/kubernetes/retriever.go
Labels: enhancement, controller

#54 feat(control loop): add the control loop of the watcher
  internal/kubernetes/retriever.go
  internal/kubernetes/retriever_test.go
  internal/kubernetes/watcher.go
Labels: enhancement, controller, test

#76 ci(linter): change the ci linting job to use super linter
  .github/workflows/ci.yaml
  .github/workflows/test-and-push.yaml
  internal/kubernetes/job.go
  internal/kubernetes/labeller.go
  internal/kubernetes/labeller_test.go
  internal/kubernetes/retriever_test.go
  internal/kubernetes/watcher_test.go
  internal/structure/set_test.go
Labels: enhancement, refactoring

#77 ci(unit test): add golang unit tests
  .github/workflows/ci.yaml
Labels: enhancement, test

#79 ci(cleaning): add unit testing, nightly scans, and dynamic image building
  .github/configs/paths.yaml
  .github/workflows/ci.yaml
  .github/workflows/nightly-scan.yaml
  .github/workflows/trivy-scan.yaml
Labels: research, test, refactoring

#84 refactor: add comments and improve code
  cmd/controller/main.go
  cmd/scheduler/main.go
  internal/kubernetes/job.go
  internal/kubernetes/labeller.go
  internal/kubernetes/retriever.go
  internal/kubernetes/retriever_test.go
  internal/kubernetes/watcher.go
  internal/structure/configs.go
  internal/structure/set.go
Labels: refactoring

#97 docs(readme): add documentation to follow OSS standards
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  SECURITY.md
Labels: documentation
